### PR TITLE
LH2NTRsDynamic.cfg

### LINKED ISSUE #27: add LH2 patch to Vens stock revamp NTRs

### PR DESCRIPTION
**Pull request by toric55**
simply changes any LF-only engine to use LH2 at the same mass flow. fixes #27 and #26.

### CODE REVIEW

**Comment by ChrisAdderley** [comment]
Needs some more work to function as a global solution. However if this is done it'll be good as i can remove all of the non-handcrafted configs

1. Don't use FINAL, use AFTER so that a later patch can target this
2. You need to increase the Isp of the engines by ~10-20% when doing this, and decrease their mass by ~25%... the mass ratio of LH2 requires these buffs
3. Devise a "reversion" patch to go in Extras/NTRsUseLF to undoes or disables these changes
4. Make sure this doesn't touch anything thats already patched to LH2, is an atmospheric engine, etc... (just testing here)

**Comment by toric55** [comment]
ok. the patch can be disabled by adding :FOR[NTRsUseLF] to any patch.

can use after, as :AFTER[KerbalAtomics] could leave out engined added by mods that come alphabetically after kerbalatomics, sutch as quiztech areospace and vens stock revamp. (MM seems to do things alphabetically)

added the mass modification, but MM doesnt seem to like me attempting to multiply the atmospherecurve. if it is possible, might have to mess around with variables or something... ill have to dig more.

**Comment by toric55** [comment]
ok. changed FINAL to FOR, and MM does things in aphebetical order, based on either the folder they are withing or the FOR notation, so zz should allow any zzz patch to change it. 
also added a 10% ISP buff to the NTRs. (may mess up if the atmospherecurves have tangents.) thanks to sigma88 and blowfish for this one!

**Comment by toric55** [comment]
@ChrisAdderley, been testing this with various modpacks that are not included in the default patches, and have found nothing wrong so far.

**Comment by ChrisAdderley** [comment]
Good to know! We still need to do 2 things 
1) target to dev
2) add a new patch to the Extras to undo these changes under the NTRsUseLFs section

**Comment by toric55** [comment]
can already be disabled with a patch that uses :FOR[NTRsUseLF].
what do you mean by target to dev? do you mean target the PR to the dev branch?

**Comment by ChrisAdderley** [comment]
Ah alright.

**Comment by ChrisAdderley** [comment]
Just an FYI - I'm deprecating all the patches that don't need specific custom stuff in favour of yours. Nice work :)

**Pull request merged**
