### PR TITLE
MM Patch order for NTRsUseLF and NFE Extras

### PR DESCRIPTION
**Pull request by HSJasperism**
to prevent the file /GameData/KerbalAtomics/Patches/NTR/hydrogenNTRsSQUAD.cfg (which is :FOR[zzLH2NTR]) from undoing changes to the mass of this engine

### CODE REVIEW

**Comment by ChrisAdderley** [comment]
Is this actually required? I am under the impression that `AFTER: KerbalAtomics` should cause this patch file to run after the patches in KA, because LH2NTRs is inside this folder

**Comment by HSJasperism** [comment]
From what I understand from the other patches, the NFE Extras support adds Uranium as a resource while also subtracting the weight of the amount added.

But upon checking in-game mass (~2.8 tons instead of ~2.25 tons) and the KSP.log, module manager treats zzLH2NTR and Kerbal Atomics as separate mods, and will respect folders after respecting the First, Before, For, After, or Final MM tags (in that order). The NFE patch set :AFTER[KERBALATOMICS] would subtract 0.55 tons, then ZZLH2NTR would hard set the dry mass back to 2.25 tons

- Line 13304
[LOG 2019-02-16 16:58:10.568] :AFTER[KERBALATOMICS] pass

- Line 13564:
[LOG 2019-02-16 16:58:12.642] :AFTER[ZZLH2NTR] pass

(note the log below already has the :AFTER[zzLH2NTR] change, and the Extras folder inside KerbalAtomics renamed to zExtras - this has the stock nuclearEngine at ~2.25 tons wet mass)

[KSP.log](https://github.com/ChrisAdderley/KerbalAtomics/files/2872402/KSP.log)

(Sorry about the bloated log size though)

**Comment by ChrisAdderley** [comment]
Oh okay. This might be a problem with the other patch then. I notice the LH2 converters say something like.
```@PART[nuclearEngine]:NEEDS[!NTRsUseLF]:FOR[zzLH2NTR]```
`FOR` defines a new MM pass, so that's why it's happening. This could probably be removed if we check to make sure that the ordering is correct in other cases. It should be
1. Check for presence of NTRsUseLF
2. If yes, patch KA engines to LF
3. If no, patch other engines to LH2
4. Apply NFE Extras patch 
It seems to me that because order doesn't matter in any but the last operation, all the for/after specifiers could be removed except that one.

**Comment by HSJasperism** [comment]
> 1. Check for presence of NTRsUseLF
> 2. If yes, patch KA engines to LF
> 3. If no, patch other engines to LH2
> 4. Apply NFE Extras patch

OK, got it. Thanks for troubleshooting the issue. I'll check the Patches and Extras folders to make sure they follow the above load order. I'll make a new pull request after I test the load orders in game.

**Comment by HSJasperism** [comment]
Good day. I've managed to run KSP with no major errors. Issue #60 seems to be related to CKAN placing the Extras folder inside KerbalAtomics, so I've added :FOR[NTRsUseLF] to the config so that the folder structure won't matter. I'll post KSP.log as soon as I can verify there are no more issues.

**Comment by HSJasperism** [comment]
No issues found during gameplay, though I have not tested the configs for 3rd party parts.

**Comment by ChrisAdderley** [comment]
Thanks for all your efforts!

**Pull request merged**
